version: '3.8'

volumes:
  planefence:
  readsbpb_rrd:
  readsbpb_autogain:

services:
  planefence:
    image: kx1t/planefence
    tty: true
    container_name: planefence
    hostname: planefence
    restart: always
    ports:
      - 8088:80
    env_file: .env
    environment:
      - TZ=${FEEDER_TZ}
    volumes:
      - planefence:/usr/share/planefence/persist
      - /opt/planefence/Volumes/html:/usr/share/planefence/html
    tmpfs:
      - /run:rw,nosuid,nodev,exec,relatime,size=128M
      - /tmp:rw,nosuid,nodev,noexec,relatime,size=128M

  readsb:
    image: mikenye/readsb-protobuf:latest
    tty: true
    container_name: readsb
    hostname: readsb
    restart: always
    devices:
      - /dev/bus/usb
    ports:
      - 8080:8080
      - 30003:30003
    environment:
      - TZ=${FEEDER_TZ}
      - READSB_DEVICE_TYPE=rtlsdr
      - READSB_RTLSDR_DEVICE=stx:1090:38
      - READSB_GAIN=autogain
      - READSB_LAT=${FEEDER_LAT}
      - READSB_LON=${FEEDER_LONG}
      - READSB_RX_LOCATION_ACCURACY=2
      - READSB_STATS_RANGE=true
      - READSB_NET_ENABLE=true
      - READSB_NET_CONNECTOR=dump978,37981,raw_in
      - READSB_NET_SBS_OUTPUT_PORT=30003
      - READSB_EXTRA_ARGS=--net-beast-reduce-interval 2 --net-sbs-reduce
    volumes:
      - readsbpb_rrd:/run/collectd
      - readsbpb_autogain:/run/autogain
